Controllers/Applicant_AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CommercialApp.Models;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;
using CommercialApp.DataAccess;

namespace CommercialApp.Controllers
{
    public class Applicant_AddressController : Controller
    {
        // GET: Applicant_Address
        [HttpGet]
        public ActionResult AAddressView(string aname)
        {
            Applicant_Address applicantaddObj = new Applicant_Address();
            using (SqlConnection con = new SqlConnection("Data Source=RAHUL\\SQLEXPRESS01;Initial Catalog=Commercial;Integrated Security=True"))
            {
                string sqlQuery = "select * from APPLICANT where first_name='" + aname + "'";
                con.Open();
                SqlCommand sqlCmd = new SqlCommand(sqlQuery, con);
                SqlDataReader sdr = sqlCmd.ExecuteReader();
                if (sdr.Read())
                {
                    applicantaddObj.applicant_id = Convert.ToInt32(sdr["applicant_id"]);
                    applicantaddObj.role = Convert.ToString(sdr["role"]);
                    applicantaddObj.ssn = Convert.ToInt32(sdr["ssn"]);
                }
                con.Close();
            }

            return View(applicantaddObj);
        }

        [HttpPost]
        public ActionResult AAddressView(Applicant_Address app_address)
        {
            if (ModelState.IsValid) //checking model is valid or not
            {
                DataAccessLayer objDB = new DataAccessLayer();
                string result = objDB.InsertAData(app_address);
                ViewData["result"] = result;
                ModelState.Clear(); //clearing model
                //return View();
                return RedirectToAction("PayrollView", "Payroll", new { bname = @Session["business_name"] });
            }
            else
            {
                ModelState.AddModelError("", "Error in saving data");
                return View();
            }
        }

        public ActionResult AWelcome()
        {
            return View();
        }
    }
}

Controllers/BusinessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CommercialApp.Models;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;

namespace CommercialApp.Controllers
{
    public class BusinessController : Controller
    {
        // GET: Business
       /* public ActionResult BusinessView()
        {
            return View();
        }*/
        [HttpGet]
        public ActionResult BusinessView(string name)
        {
            Business businessObj = new Business();
            using (SqlConnection con = new SqlConnection("Data Source=RAHUL\\SQLEXPRESS01;Initial Catalog=Commercial;Integrated Security=True"))
            {
                string sqlQuery = "select * from APPLICANT where first_name='" + name + "'";
                con.Open();
                SqlCommand sqlCmd = new SqlCommand(sqlQuery, con);
                SqlDataReader sdr = sqlCmd.ExecuteReader();
                if (sdr.Read())
                {        
                    businessObj.applicant_id = Convert.ToInt32(sdr["applicant_id"]);
                }
                con.Close();
            }

                return View(businessObj);
        }

        [HttpPost]
        public ActionResult BusinessView(Business business)
        {
            using (SqlConnection con = new SqlConnection("Data Source=RAHUL\\SQLEXPRESS01;Initial Catalog=Commercial;Integrated Security=True"))
            {
                // Insert query  
                string query = "INSERT INTO BUSINESS(business_name,industry_type,TIN,number_of_employees,business_entity_type,date_of_establishment,turnover_amount,applicant_id,annual_revenue) VALUES(@bname,@itype,@tin,@nofemployees,@bentity,@date,@tamount,@applicant_id,@annual_revenue)";
                //using stored procedure
                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    cmd.Connection = con;
                    // opening connection  
                    con.Open();
                    //cmd.CommandType = CommandType.StoredProcedure;
                    // Passing parameter values  
                    cmd.Parameters.AddWithValue("@bname", business.business_name);
                    cmd.Parameters.AddWithValue("@itype", business.indsustry_type);
                    cmd.Parameters.AddWithValue("@tin", business.tin);
                    cmd.Parameters.AddWithValue("@nofemployees", business.number_of_employees);
                    cmd.Parameters.AddWithValue("@bentity", business.business_entity_type);
                    cmd.Parameters.AddWithValue("@date", business.date_of_establishment);
                    cmd.Parameters.AddWithValue("@tamount", business.turnover_amount);
                    cmd.Parameters.AddWithValue("@annual_revenue", business.annual_revenue);
                    cmd.Parameters.AddWithValue("@applicant_id", business.applicant_id);
                    //cmd.Parameters.AddWithValue("@Query", 1);
                    // Executing stored procedure 
                    cmd.ExecuteNonQuery();
                    //status = (cmd.ExecuteNonQuery() >= 1) ? "Record is saved Successfully!" : "Record is not saved";

                    //status += "<br/>";
                    Session["business_name"] = business.business_name;
                    return RedirectToAction("BAddressView", "Business_Address", new { bname = @Session["business_name"] });

                }
                /*
                using (SqlCommand cmdd = new SqlCommand("select * from APPLICANT where first_name="+ applicant.first_name,con))
                {
                    cmdd.Connection = con;
                    //con.Open();
                    SqlDataReader sdr = cmdd.ExecuteReader();
                    if (sdr.Read())
                    {
                        Session["applicant_id"] = sdr["applicant_id"].ToString();
                        
                    }
                   
                }
                
              */
                con.Close();
            }
            return View();
        }

        public ActionResult BWelcome()
        {
            return View();
        }
    }
}

Controllers/Business_AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CommercialApp.Models;
using System.Configuration;
using System.Data.SqlClient;
using CommercialApp.DataAccess;


namespace CommercialApp.Controllers
{
    public class Business_AddressController : Controller
    {
        // GET: Business_Address
        [HttpGet]
        public ActionResult BAddressView(string bname)
        {
            Business_Address businessaddObj = new Business_Address();
            using (SqlConnection con = new SqlConnection("Data Source=RAHUL\\SQLEXPRESS01;Initial Catalog=Commercial;Integrated Security=True"))
            {
                string sqlQuery = "select * from BUSINESS where business_name='" + bname + "'";
                con.Open();
                SqlCommand sqlCmd = new SqlCommand(sqlQuery, con);
                SqlDataReader sdr = sqlCmd.ExecuteReader();
                if (sdr.Read())
                {
                    businessaddObj.business_id = Convert.ToInt32(sdr["business_id"]);
                }
                con.Close();
            }

            return View(businessaddObj);
        }
        [HttpPost]
        public ActionResult BAddressView(Business_Address Bu_address)
        {
            if (ModelState.IsValid) //checking model is valid or not
            {
                DataAccessLayer objDB = new DataAccessLayer();
                string result = objDB.InsertData(Bu_address);
                ViewData["result"] = result;
                ModelState.Clear(); //clearing model
                //return View();
                return RedirectToAction("AAddressView", "Applicant_Address", new { aname = @Session["first_name"] });
            }
            else
            {
                ModelState.AddModelError("", "Error in saving data");
                return View();
            }
        }

        public ActionResult BAWelcome()
        {
            return View();
        }
    }
}

Views/Business_Address/BAWelcome.cshtml

@{
    ViewBag.Title = "BAWelcome";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Hey @Session["first_name"]</h2>
<h3>To give Your Personal Information..click NEXT </h3>
<div>
    @Html.ActionLink("NEXT", "AAddressView", "Applicant_Address", new { aname = @Session["first_name"] }, new { @class = "welcome-links" })
</div>


Views/Business_Address/BAddressView.cshtml
@model CommercialApp.Models.Business_Address

@{
    ViewBag.Title = "BAddressView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<style>
    /* Latest compiled and minified CSS included as External Resource*/
    /* Optional theme */
    body {
        margin-top: 30px;
    }

    .stepwizard-step p {
        margin-top: 0px;
        color: #666;
    }

    .stepwizard-row {
        display: table-row;
    }

    .stepwizard {
        display: table;
        width: 100%;
        position: relative;
    }

    .stepwizard-step button[disabled] {
        /*opacity: 1 !important;
    filter: alpha(opacity=100) !important;*/
    }

    .stepwizard .btn.disabled, .stepwizard .btn[disabled], .stepwizard fieldset[disabled] .btn {
        opacity: 1 !important;
        color: #bbb;
    }

    .stepwizard-row:before {
        top: 14px;
        bottom: 0;
        position: absolute;
        content: " ";
        width: 100%;
        height: 1px;
        background-color: #ccc;
        z-index: 0;
    }

    .stepwizard-step {
        display: table-cell;
        text-align: center;
        position: relative;
    }

    .btn-circle {
        width: 30px;
        height: 30px;
        text-align: center;
        padding: 6px 0;
        font-size: 12px;
        line-height: 1.428571429;
        border-radius: 15px;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="container">
    <div class="stepwizard">
        <div class="stepwizard-row setup-panel">
            <div class="stepwizard-step col-xs-1">
                <a href="#step-1" type="button" class="btn btn-info btn-circle">1</a>
                <p><small>Application</small></p>
            </div>
            <div class="stepwizard-step col-xs-2">
                <a href="#step-2" type="button" class="btn btn-success btn-circle">2</a>
                <p><small>Business Information</small></p>
            </div>
            <div class="stepwizard-step col-xs-1">
                <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
                <p><small>Personal Information</small></p>
            </div>
            <div class="stepwizard-step col-xs-2">
                <a href="#step-4" type="button" class="btn btn-default btn-circle" disabled="disabled">4</a>
                <p><small>Payroll calculation</small></p>
            </div>
            <div class="stepwizard-step col-xs-1">
                <a href="#step-5" type="button" class="btn btn-default btn-circle" disabled="disabled">5</a>
                <p><small>Loan Information</small></p>
            </div>
            <div class="stepwizard-step col-xs-2">
                <a href="#step-6" type="button" class="btn btn-default btn-circle" disabled="disabled">6</a>
                <p><small>Account Information</small></p>
            </div>
            <div class="stepwizard-step col-xs-1">
                <a href="#step-7" type="button" class="btn btn-default btn-circle" disabled="disabled">7</a>
                <p><small>Beneficiary ownership</small></p>
            </div>
            <div class="stepwizard-step col-xs-2">
                <a href="#step-8" type="button" class="btn btn-default btn-circle" disabled="disabled">8</a>
                <p><small>Summary</small></p>
            </div>
        </div>
    </div>

    <br /><br />
    <form role="form">
        <div class="panel panel-primary setup-content" id="step-2">

            <div class="panel-heading">
                <h3 class="panel-title">Paycheck Protection Program Loan Application</h3>
            </div>

            <div class="form-horizontal">
                <h4><b>Where is your Business is Located?</b></h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.street_address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.street_address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.street_address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                        @Html.LabelFor(model => model.state, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
                        </div>
                </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.zipcode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.zipcode, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.zipcode, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.business_id, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.business_id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.business_id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="CONTINUE" class="btn btn-primary nextBtn" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
     </div>
        }

<div>
    @Html.ActionLink("NEXT", "AAddressView", "Appliacnt_Address", new { aname = @Session["first_name"] })
    <br />
    @Html.ActionLink("BACK", "BusinessView", "Business")
</div>