Models/PayrollInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CommercialApp.Models
{
    public class PayrollInfo
    {
        [Display(Name = "Annual Payroll")]
        public int annual_payroll { get; set; }
        [Display(Name = "Monthly Payroll")]
        public int monthly_payroll { get; set; }
        [Display(Name = "Business_id")]
        public int business_id { get; set; }

    }
}

Controllers/PayrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CommercialApp.Models;
using System.Configuration;
using System.Data.SqlClient;
using CommercialApp.DataAccess;
using System.Data;

namespace CommercialApp.Controllers
{
    public class PayrollController : Controller
    {
        // GET: Payroll
        [HttpGet]
        public ActionResult PayrollView(string bname)
        {
            Payroll pObj = new Payroll();
            using (SqlConnection con = new SqlConnection("Data Source=RAHUL\\SQLEXPRESS01;Initial Catalog=Commercial;Integrated Security=True"))
            {
                string sqlQuery = "select * from BUSINESS where business_name='" + bname + "'";
                con.Open();
                SqlCommand sqlCmd = new SqlCommand(sqlQuery, con);
                SqlDataReader sdr = sqlCmd.ExecuteReader();
                if (sdr.Read())
                {
                    pObj.business_id = Convert.ToInt32(sdr["business_id"]);
                    pObj.annual_revenue= Convert.ToInt32(sdr["annual_revenue"]);
                    pObj.no_of_employees= Convert.ToInt32(sdr["number_of_employees"]);
                }
                con.Close();
            }
            return View(pObj);
        }

        [HttpPost]
        public ActionResult PayrollView(Payroll payroll)
        {
            using (SqlConnection con = new SqlConnection("Data Source=RAHUL\\SQLEXPRESS01;Initial Catalog=Commercial;Integrated Security=True"))
            {
                //using stored procedure
                using (SqlCommand cmd = new SqlCommand("calcul", con))
                {
                    cmd.Connection = con;
                    // opening connection  
                    con.Open();
                    cmd.CommandType = CommandType.StoredProcedure;
                    // Passing parameter values  
                    cmd.Parameters.AddWithValue("@business_id", payroll.business_id);
                    cmd.Parameters.AddWithValue("@annual_revenue", payroll.annual_revenue);
                    cmd.Parameters.AddWithValue("@aggregate_amount", payroll.aggregate_amount);
                    cmd.Parameters.AddWithValue("@no_of_employees", payroll.no_of_employees);
                    // Executing stored procedure 
                    cmd.ExecuteNonQuery();
                    //status = (cmd.ExecuteNonQuery() >= 1) ? "Record is saved Successfully!" : "Record is not saved";
                    //status += "<br/>";
                    Session["b_id"] = payroll.business_id;
                    return RedirectToAction("PayrollInfoView","PayrollInfo", new { bid = @Session["b_id"] });
                }
                
                con.Close();
            }
            return View();
        }

        public ActionResult PWelcome()
        {
            return View();
        }
    }
}

Controllers/PayrollInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CommercialApp.Models;
using System.Configuration;
using System.Data.SqlClient;
using CommercialApp.DataAccess;
using System.Data;


namespace CommercialApp.Controllers
{
    public class PayrollInfoController : Controller
    {
        // GET: PayrollInfo
        [HttpGet]
        public ActionResult PayrollInfoView(string bid)
        {
            PayrollInfo piObj = new PayrollInfo();
            using (SqlConnection con = new SqlConnection("Data Source=RAHUL\\SQLEXPRESS01;Initial Catalog=Commercial;Integrated Security=True"))
            {
                string sqlQuery = "select * from PAYROLL where business_id='" + bid + "'";
                con.Open();
                SqlCommand sqlCmd = new SqlCommand(sqlQuery, con);
                SqlDataReader sdr = sqlCmd.ExecuteReader();
                if (sdr.Read())
                {
                    piObj.business_id = Convert.ToInt32(sdr["business_id"]);
                    piObj.annual_payroll = Convert.ToInt32(sdr["annual_payroll"]);
                    piObj.monthly_payroll = Convert.ToInt32(sdr["monthly_payroll"]);
                }
                con.Close();
            }
            return View(piObj);
        }
        [HttpPost]
        public ActionResult PayrollInfoView()
        {
            return RedirectToAction("LoanView", "Loan", new { bid = @Session["b_id"] });
        }
    }
}

Views/PayrollInfo/PayrollInfoView.cshtml
@model CommercialApp.Models.PayrollInfo

@{
    ViewBag.Title = "PayrollInfoView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<style>
    /* Latest compiled and minified CSS included as External Resource*/
    /* Optional theme */
    body {
        margin-top: 30px;
    }

    .stepwizard-step p {
        margin-top: 0px;
        color: #666;
    }

    .stepwizard-row {
        display: table-row;
    }

    .stepwizard {
        display: table;
        width: 100%;
        position: relative;
    }

    .stepwizard-step button[disabled] {
        /*opacity: 1 !important;
    filter: alpha(opacity=100) !important;*/
    }

    .stepwizard .btn.disabled, .stepwizard .btn[disabled], .stepwizard fieldset[disabled] .btn {
        opacity: 1 !important;
        color: #bbb;
    }

    .stepwizard-row:before {
        top: 14px;
        bottom: 0;
        position: absolute;
        content: " ";
        width: 100%;
        height: 1px;
        background-color: #ccc;
        z-index: 0;
    }

    .stepwizard-step {
        display: table-cell;
        text-align: center;
        position: relative;
    }

    .btn-circle {
        width: 30px;
        height: 30px;
        text-align: center;
        padding: 6px 0;
        font-size: 12px;
        line-height: 1.428571429;
        border-radius: 15px;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="stepwizard">
            <div class="stepwizard-row setup-panel">
                <div class="stepwizard-step col-xs-1">
                    <a href="#step-1" type="button" class="btn btn-info btn-circle">1</a>
                    <p><small>Application</small></p>
                </div>
                <div class="stepwizard-step col-xs-2">
                    <a href="#step-2" type="button" class="btn btn-info btn-circle">2</a>
                    <p><small>Business Information</small></p>
                </div>
                <div class="stepwizard-step col-xs-1">
                    <a href="#step-3" type="button" class="btn btn-info btn-circle">3</a>
                    <p><small>Personal Information</small></p>
                </div>
                <div class="stepwizard-step col-xs-2">
                    <a href="#step-4" type="button" class="btn btn-success btn-circle">4</a>
                    <p><small>Payroll calculation</small></p>
                </div>
                <div class="stepwizard-step col-xs-1">
                    <a href="#step-5" type="button" class="btn btn-default btn-circle" disabled="disabled">5</a>
                    <p><small>Loan Information</small></p>
                </div>
                <div class="stepwizard-step col-xs-2">
                    <a href="#step-6" type="button" class="btn btn-default btn-circle" disabled="disabled">6</a>
                    <p><small>Account Information</small></p>
                </div>
                <div class="stepwizard-step col-xs-1">
                    <a href="#step-7" type="button" class="btn btn-default btn-circle" disabled="disabled">7</a>
                    <p><small>Beneficiary ownership</small></p>
                </div>
                <div class="stepwizard-step col-xs-2">
                    <a href="#step-8" type="button" class="btn btn-default btn-circle" disabled="disabled">8</a>
                    <p><small>Summary</small></p>
                </div>
            </div>
        </div>
        <br />
        <br />
        <form role="form">
            <div class="panel panel-primary setup-content" id="step-4">

                <div class="panel-heading">
                    <h3 class="panel-title">Paycheck Protection Program Loan Application</h3>
                </div>

                <div class="form-horizontal">
                    <h4><b>Payroll Information</b></h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.annual_payroll, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.annual_payroll, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.annual_payroll, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.monthly_payroll, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.monthly_payroll, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.monthly_payroll, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.business_id, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.business_id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.business_id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="CONTINUE" class="btn btn-primary nextBtn" />
                        </div>
                    </div>
                </div>
                </div>
            </form>
        </div>
                }

                <div>
                    @Html.ActionLink("BACK", "PayrollView","Payroll")
                </div>